<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>bon de commande</title>
</head>
<body>
    <table>
        <thead>
            <th>Order Number</th>
            <th>Order Date</th>
            <th>Status </th>
            <th>Shipped Date </th>
        </thead>

        
        <?php foreach ($results as $result):?>
            <tr>
                <td><a href="detail.php?id=<?=$result['orderNumber']?>"><?= $result['orderNumber']; ?></td>
                <td><?= $result['orderDate']; ?></td>
                <td><?= $result['status']; ?></td>
                <td><?= $result['shippedDate']; ?></td>
            </tr>
        <?php endforeach; ?>    


    </table>
</body>
</html>